name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
         - 1.31.1
         - stable
         - beta
    steps:
    - name: Download and install Pandoc
      run: curl -L https://github.com/jgm/pandoc/releases/download/2.4/pandoc-2.4-1-amd64.deb --output pandoc-2.4-1-amd64.deb && \
           echo '2d53c645895eacfe4bff572f7ccd5050890248c37be311f3d04819e11dcd97f7  pandoc-2.4-1-amd64.deb' > pandoc-2.4-1-amd64.sha256 && \
           sha256sum --check pandoc-2.4-1-amd64.sha256 && \
           rm -f pandoc-2.4-1-amd64.sha256 && \
           sudo dpkg -i pandoc-2.4-1-amd64.deb
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
